name: ROS Bloom Release

on:
  push:
    tags:
      # ROS versions follow semantic versioning
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repo with submodules
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # Install bloom
      - name: Install bloom
        run: sudo apt-get update && sudo apt-get install -y python3-bloom

      # Save authentication so bloom can login
      - name: Authenticate Bloom
        run: |
          echo '{ "github_user": "${GITHUB_USERNAME}", "oauth_token": "${GITHUB_PASSWORD}" }' > ~/.config/bloom
        env:
          GITHUB_USERNAME: ${{ secrets.MICROSTRAIN_GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.MICROSTRAIN_GITHUB_PASSWORD }}

      # Release melodic
      - name: Release Melodic
        run: bloom-release --rosdistro melodic --track melodic microstrain_inertial --no-web --non-interactive -s
        
      # Release noetic
      - name: Release Noetic
        run: bloom-release --rosdistro noetic --track noetic microstrain_inertial --no-web --non-interactive -s